
---
  version: '3.5'
  secrets:
    ssl_crt:
      file: ./config/certificates/wildcard-dev.crt
    ssl_key:
      file: ./config/certificates/wildcard-dev.key

  services:
    mlr-python-base:
      build: .
      image: mlr-python-base
      container_name: mlr-python-base
      secrets:
        - source: ssl_crt
          target: /home/python/certificates/wildcard-ssl.crt
        - source: ssl_key
          target: /home/python/certificates/wildcard-ssl.key
      env_file:
        - config.env
        - secrets.env
      ports:
        - "8000:8000"
